/**
 * Survival Mode Sector Names
 * Displayed every 750 meters in sequential order
 */

export const SURVIVAL_SECTOR_NAMES = [
  "FORBIDDEN ZONE",
  "SIGNAL LOST",
  "SECTOR DELTA-7",
  "YOU SHOULD TURN BACK",
  "VECTOR RANGE EXCEEDED",
  "UNCHARTED SPACE",
  "THIS WAS A MISTAKE",
  "FINAL APPROACH SECTOR",
  "ECHO REGION",
  "DATA CORRUPTION ZONE",
  "PROCEED WITH CAUTION",
  "LAST KNOWN COORDINATES",
  "NAV GRID DISTORTED",
  "ARE YOU SURE",
  "OUTER PERIMETER",
  "NO RETURN POINT",
  "FLIGHT PATH UNSTABLE",
  "THIS LOOKS BAD",
  "CONTROLLED REGION",
  "TELEMETRY UNRELIABLE",
  "GHOST CORRIDOR",
  "STILL ALIVE… GOOD",
  "RESTRICTED AIRSPACE",
  "ABANDONED TRAJECTORY",
  "MANUAL OVERRIDE ONLY",
  "WHAT COULD GO WRONG",
  "DEEP SURVIVAL REGION",
  "AUTHORIZATION REQUIRED",
  "SYSTEM LATENCY AREA",
  "SILENT ORBIT",
  "HOLD IT TOGETHER",
  "EXTREME ENVIRONMENT",
  "MEMORY SECTOR 3",
  "YOU'RE STILL HERE",
  "DRIFTING TERRITORY",
  "AUTO-CORRECT FAILED",
  "FINAL SURVIVAL BAND",
  "CRITICAL FLIGHT ZONE",
  "DO NOT ENTER",
  "NAVIGATION DEAD ZONE",
  "KEEP IT STEADY",
  "DARK TRANSMISSION",
  "NO FURTHER WARNINGS",
  "GUIDANCE SYSTEM ACTIVE",
  "EXCLUSION RING",
  "MAXIMUM DIFFICULTY",
  "UNSUPPORTED OPERATION",
  "ENDURANCE TEST",
  "BEYOND SAFE LIMITS",
  "SECTOR ALPHA-9"
];

export const SECTOR_INTERVAL = 750; // meters between sector announcements

/**
 * Get the sector name for a given sector index
 * @param sectorIndex - The sector number (0 = first sector at 750m)
 */
export function getSectorName(sectorIndex: number): string {
  return SURVIVAL_SECTOR_NAMES[sectorIndex % SURVIVAL_SECTOR_NAMES.length];
}
